<?php
$plan = [
  'name'           => 'Website + ERP Combo',
  'badge'          => '<i class="fa-solid fa-fire"></i> Best Value Deal',
  'badge_bg'       => 'rgba(255,210,0,0.1)',
  'badge_color'    => '#ffd200',
  'badge_border'   => 'rgba(255,210,0,0.3)',
  'title_gradient' => 'linear-gradient(90deg,#ffd200,#ff6b00)',
  'accent'         => '#ffd200',
  'description'    => 'The complete digital school package — a professional website AND the full ERP system together at an exclusive combo price. Everything your school needs, in one deal.',
  'price_display'  => 'Rs. 1,999 + Rs.10/student',
  'price_period'   => 'website setup + ERP per student/month',
  'price_old'      => 'Website alone: Rs. 5,999',
  'price_save'     => '🎉 Save Rs. 4,000 on website!',
  'domain_note'    => '* Domain registration charges are excluded',
  'btn_bg'         => 'linear-gradient(90deg,#f7971e,#ffd200)',
  'btn_text'       => 'Grab Combo Deal Now',
  'tab_color'      => 'gold',
  'features' => [
    ['<i class="fa-solid fa-globe" style="color:#3b82f6"></i>','Full school website'],
    ['<i class="fa-solid fa-school" style="color:#a855f7"></i>','Complete ERP system'],
    ['<i class="fa-solid fa-bolt" style="color:#fbbf24"></i>','Single unified dashboard'],
    ['<i class="fa-solid fa-money-bill-wave" style="color:#10b981"></i>','Fee collection & tracking'],
    ['<i class="fa-solid fa-clipboard-check" style="color:#10b981"></i>','Attendance system'],
    ['<i class="fa-solid fa-mobile-screen" style="color:#ec4899"></i>','Parent portal'],
    ['<i class="fa-solid fa-gift" style="color:#f97316"></i>','Free onboarding session'],
    ['<i class="fa-solid fa-trophy" style="color:#fbbf24"></i>','Priority support'],
  ],
  'tc' => [

    /* ====== ENGLISH ====== */
    'en' => [
      ['title'=>'Service Overview','text'=>'The Combo Plan bundles together a professional school website with the complete Schoozie ERP system at an exclusive discounted price. You get the best of both worlds — a public-facing school website and a powerful backend management system — in a single, seamless package.'],
      ['title'=>'Combo Pricing Breakdown','points'=>[
        'Website setup fee: Rs. 1,999 (one-time) — saving Rs. 4,000 vs standalone price.',
        'ERP system: Rs. 10 per active student per month.',
        'Example: 100 students = Rs. 1,999 setup + Rs. 1,000/month ongoing.',
        'Both services are active under one account and one admin dashboard.',
        'Domain registration and renewal charges are NOT included.',
      ]],
      ['title'=>'Payment Terms','points'=>[
        'Website setup fee of Rs. 1,999 must be paid upfront before work begins.',
        'ERP monthly billing starts after the free trial period ends.',
        'Payment accepted via bank transfer, JazzCash, or EasyPaisa.',
        'Both services will be activated within 24–48 hours of confirmed payment.',
      ]],
      ['title'=>'What Is Included — Website','points'=>[
        'Custom-designed school website (up to 8 pages).',
        'Mobile-friendly, responsive layout.',
        'News, events, photo gallery, admissions form.',
        'Staff and faculty profiles.',
        'First year of web hosting included.',
        'Domain setup and configuration assistance.',
      ]],
      ['title'=>'What Is Included — ERP','points'=>[
        'Student registration and profile management.',
        'Staff and teacher management.',
        'Fee collection, receipts, and automated reminders.',
        'Attendance system with daily reports.',
        'Exam management and result publishing.',
        'Parent portal — fees, attendance, results.',
        'SMS and in-app notification system.',
        'Admin dashboard with full analytics.',
        'Cloud data backup.',
      ]],
      ['title'=>'What Is NOT Included','points'=>[
        'Domain name purchase or annual renewal.',
        'Biometric hardware setup.',
        'Custom mobile app development.',
        'Third-party integrations unless agreed separately.',
        'Printed reports or physical documents.',
        'SEO optimization or paid marketing services.',
      ]],
      ['title'=>'Free Onboarding Session','text'=>'Combo plan clients receive a free onboarding session (via WhatsApp video call or in-person if local). This session covers website handover, ERP setup walkthrough, and admin panel training. The session is scheduled within 3 days of project delivery.'],
      ['title'=>'Priority Support','points'=>[
        'Combo clients receive priority support over standard plan clients.',
        'Response time within 12 hours on working days.',
        'Critical issues addressed within 4 hours.',
        'Support available via WhatsApp (Mon–Sat, 10am–6pm IST).',
        '30-day post-launch dedicated support included.',
      ]],
      ['title'=>'Delivery Timeline','points'=>[
        'Website delivered within 10–14 working days of payment and content submission.',
        'ERP system activated within 24–48 hours of payment.',
        'Both services run simultaneously under one admin panel.',
        'Complex customization requests may extend the website delivery timeline.',
      ]],
      ['title'=>'Hosting, Billing & Renewal','points'=>[
        'Website hosting: First year free, then annual renewal charges apply.',
        'ERP billing: Monthly, auto-renews based on active student count.',
        'Both services can be managed from a single dashboard.',
        'Schoozie will notify 30 days before hosting expiry.',
        'ERP subscription may be cancelled independently of the website if needed.',
      ]],
      ['title'=>'Data Privacy & Ownership','points'=>[
        'All client data (website content and student records) is securely stored.',
        'Schoozie will NOT share any client data with third parties.',
        'Client owns their content; Schoozie owns the design and code.',
        'Upon termination, client may request a data export within 30 days.',
      ]],
      ['title'=>'Cancellation & Refund Policy','points'=>[
        'Website setup fee (Rs. 1,999) is non-refundable once design work begins.',
        'ERP subscription can be cancelled with 7 days notice before next billing cycle.',
        'No refund for partial billing months.',
        'Full refund for setup fee only if work has not commenced and request is within 24 hours.',
      ]],
      ['title'=>'Governing Terms','text'=>'These terms are governed under Indian law. Any dispute will first be addressed through mutual discussion. Schoozie reserves the right to update these terms at any time with 30 days prior notice via WhatsApp or email.'],
    ],

    /* ====== URDU ====== */
    'ur' => [
      ['title'=>'خدمت کا جائزہ','text'=>'کومبو پلان ایک پیشہ ورانہ اسکول ویب سائٹ کو مکمل اسکوزی ERP سسٹم کے ساتھ ایک خصوصی رعایتی قیمت پر جوڑتا ہے۔ آپ کو دونوں کا بہترین ملتا ہے — ایک عوامی اسکول ویب سائٹ اور ایک طاقتور بیک اینڈ مینجمنٹ سسٹم — ایک ہی پیکج میں۔'],
      ['title'=>'کومبو قیمت کی تفصیل','points'=>[
        'ویب سائٹ سیٹ اپ فیس: ۱،۹۹۹ روپے (یکمشت) — الگ قیمت کے مقابلے میں ۴،۰۰۰ روپے کی بچت۔',
        'ERP سسٹم: فی فعال طالب علم فی ماہ ۱۰ روپے۔',
        'مثال: ۱۰۰ طلبا = ۱،۹۹۹ سیٹ اپ + ۱،۰۰۰ روپے/ماہ۔',
        'دونوں خدمات ایک اکاؤنٹ اور ایک ایڈمن ڈیش بورڈ کے تحت فعال ہیں۔',
        'ڈومین رجسٹریشن اور تجدید کے اخراجات شامل نہیں ہیں۔',
      ]],
      ['title'=>'ادائیگی کی شرائط','points'=>[
        'کام شروع ہونے سے پہلے ۱،۹۹۹ روپے کی ویب سائٹ سیٹ اپ فیس پیشگی ادا کرنی ہوگی۔',
        'ERP ماہانہ بلنگ مفت آزمائشی مدت ختم ہونے کے بعد شروع ہوگی۔',
        'ادائیگی بینک ٹرانسفر، جاز کیش یا ایزی پیسہ کے ذریعے قبول کی جاتی ہے۔',
        'ادائیگی کی تصدیق کے ۲۴ سے ۴۸ گھنٹوں کے اندر دونوں خدمات فعال ہو جائیں گی۔',
      ]],
      ['title'=>'کیا شامل ہے — ویب سائٹ','points'=>[
        'حسب ضرورت اسکول ویب سائٹ ڈیزائن (۸ صفحات تک)۔',
        'موبائل فرینڈلی، ریسپانسیو لے آؤٹ۔',
        'خبریں، تقریبات، فوٹو گیلری، داخلہ فارم۔',
        'اسٹاف اور فیکلٹی پروفائل۔',
        'پہلے سال کی ویب ہوسٹنگ شامل۔',
        'ڈومین سیٹ اپ اور کنفیگریشن میں مدد۔',
      ]],
      ['title'=>'کیا شامل ہے — ERP','points'=>[
        'طلبا کی رجسٹریشن اور پروفائل مینجمنٹ۔',
        'اسٹاف اور اساتذہ کا انتظام۔',
        'فیس کلیکشن، رسیدیں اور خودکار یاددہانیاں۔',
        'روزانہ رپورٹس کے ساتھ حاضری سسٹم۔',
        'امتحان مینجمنٹ اور نتیجہ شائع کرنا۔',
        'والدین پورٹل — فیس، حاضری، نتائج۔',
        'SMS اور ان ایپ نوٹیفکیشن سسٹم۔',
        'مکمل تجزیات کے ساتھ ایڈمن ڈیش بورڈ۔',
        'کلاؤڈ ڈیٹا بیک اپ۔',
      ]],
      ['title'=>'کیا شامل نہیں ہے','points'=>[
        'ڈومین نام کی خریداری یا سالانہ تجدید۔',
        'بائیو میٹرک ہارڈ ویئر سیٹ اپ۔',
        'کسٹم موبائل ایپ ڈویلپمنٹ۔',
        'تھرڈ پارٹی انٹیگریشن الگ معاہدے کے بغیر۔',
        'پرنٹڈ رپورٹس یا جسمانی دستاویزات۔',
        'SEO آپٹیمائزیشن یا پیڈ مارکیٹنگ خدمات۔',
      ]],
      ['title'=>'مفت آن بورڈنگ سیشن','text'=>'کومبو پلان کلائنٹس کو ایک مفت آن بورڈنگ سیشن ملتا ہے (واٹس ایپ ویڈیو کال یا ذاتی طور پر اگر مقامی ہو)۔ اس سیشن میں ویب سائٹ ہینڈ اوور، ERP سیٹ اپ واک تھرو اور ایڈمن پینل ٹریننگ شامل ہے۔ سیشن ڈیلیوری کے ۳ دنوں کے اندر شیڈول کیا جائے گا۔'],
      ['title'=>'ترجیحی سپورٹ','points'=>[
        'کومبو کلائنٹس کو معیاری پلان کلائنٹس پر ترجیحی سپورٹ ملتی ہے۔',
        'کاری دنوں میں جواب کا وقت ۱۲ گھنٹوں کے اندر۔',
        'اہم مسائل ۴ گھنٹوں کے اندر حل کیے جاتے ہیں۔',
        'سپورٹ واٹس ایپ کے ذریعے (پیر تا ہفتہ، صبح ۱۰ بجے تا شام ۶ بجے) دستیاب ہے۔',
        'لانچ کے بعد ۳۰ دنوں کی مخصوص سپورٹ شامل ہے۔',
      ]],
      ['title'=>'ڈیلیوری ٹائم لائن','points'=>[
        'ویب سائٹ ادائیگی اور مواد جمع کرانے کے ۱۰ سے ۱۴ کاری دنوں میں فراہم کی جائے گی۔',
        'ERP سسٹم ادائیگی کے ۲۴ سے ۴۸ گھنٹوں کے اندر فعال ہو جائے گا۔',
        'دونوں خدمات ایک ایڈمن پینل کے تحت بیک وقت چلتی ہیں۔',
        'پیچیدہ حسب ضرورت درخواستیں ویب سائٹ کی ڈیلیوری ٹائم لائن کو بڑھا سکتی ہیں۔',
      ]],
      ['title'=>'ہوسٹنگ، بلنگ اور تجدید','points'=>[
        'ویب سائٹ ہوسٹنگ: پہلا سال مفت، پھر سالانہ تجدید کے اخراجات۔',
        'ERP بلنگ: ماہانہ، فعال طلبا کی تعداد کی بنیاد پر خودبخود تجدید۔',
        'دونوں خدمات ایک ڈیش بورڈ سے منظم کی جا سکتی ہیں۔',
        'ہوسٹنگ کی میعاد ختم ہونے سے ۳۰ دن پہلے اسکوزی مطلع کرے گا۔',
        'ضرورت پڑنے پر ERP سبسکرپشن ویب سائٹ سے آزادانہ طور پر منسوخ کی جا سکتی ہے۔',
      ]],
      ['title'=>'ڈیٹا پرائیویسی اور ملکیت','points'=>[
        'تمام کلائنٹ ڈیٹا (ویب سائٹ مواد اور طلبا کے ریکارڈ) محفوظ طریقے سے رکھا جاتا ہے۔',
        'اسکوزی کلائنٹ کا ڈیٹا تیسرے فریق کے ساتھ شیئر نہیں کرے گا۔',
        'کلائنٹ اپنے مواد کا مالک ہے؛ اسکوزی ڈیزائن اور کوڈ کا مالک ہے۔',
        'ختم ہونے پر، کلائنٹ ۳۰ دنوں کے اندر ڈیٹا ایکسپورٹ کی درخواست کر سکتا ہے۔',
      ]],
      ['title'=>'منسوخی اور واپسی کی پالیسی','points'=>[
        'ڈیزائن کام شروع ہونے کے بعد ۱،۹۹۹ روپے کی سیٹ اپ فیس واپس نہیں ہوگی۔',
        'ERP سبسکرپشن اگلے بلنگ سائیکل سے ۷ دن پہلے اطلاع دے کر منسوخ کی جا سکتی ہے۔',
        'جزوی بلنگ مہینوں کی واپسی نہیں ہوگی۔',
        'سیٹ اپ فیس کی مکمل واپسی صرف تب ممکن ہے جب کام شروع نہ ہوا ہو اور درخواست ۲۴ گھنٹوں کے اندر ہو۔',
      ]],
      ['title'=>'حاکم شرائط','text'=>'یہ شرائط بھارتی قانون کے تحت ہیں۔ کسی بھی تنازع کو پہلے باہمی گفتگو سے حل کیا جائے گا۔ اسکوزی ۳۰ دن کی پیشگی اطلاع کے ساتھ ان شرائط کو کسی بھی وقت اپ ڈیٹ کرنے کا حق رکھتا ہے۔'],
    ],

    /* ====== HINDI ====== */
    'hi' => [
      ['title'=>'सेवा का अवलोकन','text'=>'Combo Plan एक पेशेवर स्कूल वेबसाइट को पूर्ण Schoozie ERP सिस्टम के साथ एक विशेष रियायती मूल्य पर जोड़ता है। आपको दोनों का सर्वश्रेष्ठ मिलता है — एक सार्वजनिक स्कूल वेबसाइट और एक शक्तिशाली बैकएंड प्रबंधन प्रणाली — एक ही पैकेज में।'],
      ['title'=>'कॉम्बो मूल्य विवरण','points'=>[
        'वेबसाइट सेटअप शुल्क: Rs. 1,999 (एकमुश्त) — अलग मूल्य की तुलना में Rs. 4,000 की बचत।',
        'ERP सिस्टम: प्रति सक्रिय छात्र प्रति माह Rs. 10।',
        'उदाहरण: 100 छात्र = Rs. 1,999 सेटअप + Rs. 1,000/माह।',
        'दोनों सेवाएं एक खाते और एक एडमिन डैशबोर्ड के तहत सक्रिय हैं।',
        'डोमेन पंजीकरण और नवीनीकरण शुल्क शामिल नहीं हैं।',
      ]],
      ['title'=>'भुगतान की शर्तें','points'=>[
        'काम शुरू होने से पहले Rs. 1,999 का वेबसाइट सेटअप शुल्क अग्रिम भुगतान करना होगा।',
        'ERP मासिक बिलिंग मुफ्त परीक्षण अवधि समाप्त होने के बाद शुरू होगी।',
        'भुगतान बैंक ट्रांसफर, JazzCash या EasyPaisa के माध्यम से स्वीकार किया जाता है।',
        'पुष्टि के 24-48 घंटों के भीतर दोनों सेवाएं सक्रिय हो जाएंगी।',
      ]],
      ['title'=>'क्या शामिल है — वेबसाइट','points'=>[
        'कस्टम-डिज़ाइन की गई स्कूल वेबसाइट (8 पृष्ठों तक)।',
        'मोबाइल-फ्रेंडली, रिस्पॉन्सिव लेआउट।',
        'समाचार, कार्यक्रम, फोटो गैलरी, प्रवेश फॉर्म।',
        'स्टाफ और फैकल्टी प्रोफाइल।',
        'पहले वर्ष की वेब होस्टिंग शामिल।',
        'डोमेन सेटअप और कॉन्फ़िगरेशन सहायता।',
      ]],
      ['title'=>'क्या शामिल है — ERP','points'=>[
        'छात्र पंजीकरण और प्रोफाइल प्रबंधन।',
        'स्टाफ और शिक्षक प्रबंधन।',
        'शुल्क संग्रह, रसीदें और स्वचालित अनुस्मारक।',
        'दैनिक रिपोर्ट के साथ उपस्थिति प्रणाली।',
        'परीक्षा प्रबंधन और परिणाम प्रकाशन।',
        'माता-पिता पोर्टल — शुल्क, उपस्थिति, परिणाम।',
        'SMS और इन-ऐप अधिसूचना प्रणाली।',
        'पूर्ण विश्लेषण के साथ एडमिन डैशबोर्ड।',
        'क्लाउड डेटा बैकअप।',
      ]],
      ['title'=>'क्या शामिल नहीं है','points'=>[
        'डोमेन नाम की खरीद या वार्षिक नवीनीकरण।',
        'बायोमेट्रिक हार्डवेयर सेटअप।',
        'कस्टम मोबाइल ऐप विकास।',
        'अलग समझौते के बिना थर्ड-पार्टी एकीकरण।',
        'मुद्रित रिपोर्ट या भौतिक दस्तावेज।',
        'SEO अनुकूलन या भुगतान विपणन सेवाएं।',
      ]],
      ['title'=>'मुफ्त ऑनबोर्डिंग सत्र','text'=>'Combo plan क्लाइंट्स को एक मुफ्त ऑनबोर्डिंग सत्र मिलता है (WhatsApp वीडियो कॉल या व्यक्तिगत रूप से यदि स्थानीय हो)। इस सत्र में वेबसाइट हैंडओवर, ERP सेटअप वॉकथ्रू और एडमिन पैनल प्रशिक्षण शामिल है। सत्र डिलीवरी के 3 दिनों के भीतर निर्धारित किया जाएगा।'],
      ['title'=>'प्राथमिकता सहायता','points'=>[
        'Combo क्लाइंट्स को मानक प्लान क्लाइंट्स पर प्राथमिकता सहायता मिलती है।',
        'कार्य दिवसों पर प्रतिक्रिया समय 12 घंटों के भीतर।',
        'गंभीर समस्याएं 4 घंटों के भीतर हल की जाती हैं।',
        'सहायता WhatsApp के माध्यम से (सोम-शनि, सुबह 10 - शाम 6 IST) उपलब्ध है।',
        'लॉन्च के बाद 30 दिनों की समर्पित सहायता शामिल है।',
      ]],
      ['title'=>'डिलीवरी समयसीमा','points'=>[
        'वेबसाइट भुगतान और सामग्री जमा करने के 10-14 कार्य दिवसों में वितरित की जाएगी।',
        'ERP सिस्टम भुगतान के 24-48 घंटों के भीतर सक्रिय हो जाएगा।',
        'दोनों सेवाएं एक एडमिन पैनल के तहत एक साथ चलती हैं।',
        'जटिल अनुकूलन अनुरोध वेबसाइट डिलीवरी समयसीमा बढ़ा सकते हैं।',
      ]],
      ['title'=>'होस्टिंग, बिलिंग और नवीनीकरण','points'=>[
        'वेबसाइट होस्टिंग: पहला वर्ष मुफ्त, फिर वार्षिक नवीनीकरण शुल्क लागू।',
        'ERP बिलिंग: मासिक, सक्रिय छात्र संख्या के आधार पर स्वतः नवीनीकृत।',
        'दोनों सेवाएं एक डैशबोर्ड से प्रबंधित की जा सकती हैं।',
        'होस्टिंग समाप्ति से 30 दिन पहले Schoozie सूचित करेगा।',
        'यदि आवश्यक हो तो ERP सदस्यता वेबसाइट से स्वतंत्र रूप से रद्द की जा सकती है।',
      ]],
      ['title'=>'डेटा गोपनीयता और स्वामित्व','points'=>[
        'सभी क्लाइंट डेटा (वेबसाइट सामग्री और छात्र रिकॉर्ड) सुरक्षित रूप से संग्रहीत हैं।',
        'Schoozie किसी भी क्लाइंट डेटा को तीसरे पक्ष के साथ साझा नहीं करेगा।',
        'क्लाइंट अपनी सामग्री का मालिक है; Schoozie डिज़ाइन और कोड का मालिक है।',
        'समाप्ति पर, क्लाइंट 30 दिनों के भीतर डेटा निर्यात का अनुरोध कर सकता है।',
      ]],
      ['title'=>'रद्दीकरण और धनवापसी नीति','points'=>[
        'डिज़ाइन कार्य शुरू होने के बाद Rs. 1,999 का सेटअप शुल्क वापस नहीं होगा।',
        'ERP सदस्यता अगले बिलिंग चक्र से 7 दिन पहले सूचना देकर रद्द की जा सकती है।',
        'आंशिक बिलिंग महीनों की कोई धनवापसी नहीं होगी।',
        'सेटअप शुल्क की पूर्ण धनवापसी केवल तभी संभव है जब काम शुरू न हुआ हो और अनुरोध 24 घंटों के भीतर हो।',
      ]],
      ['title'=>'शासी नियम','text'=>'ये शर्तें पाकिस्तानी कानून के तहत हैं। किसी भी विवाद को पहले आपसी बातचीत से सुलझाया जाएगा। Schoozie 30 दिन की पूर्व सूचना के साथ इन शर्तों को कभी भी अपडेट करने का अधिकार रखता है।'],
    ],
  ],
];
include '_plan_layout.php';
