<?php
$plan = [
  'name'           => 'Dynamic Website',
  'badge'          => '⚡ April Special Offer',
  'badge_bg'       => 'rgba(255,0,204,0.1)',
  'badge_color'    => '#ff00cc',
  'badge_border'   => 'rgba(255,0,204,0.3)',
  'title_gradient' => 'linear-gradient(90deg,#ff00cc,#aa00ff)',
  'accent'         => '#ff00cc',
  'description'    => 'Your school gets its own powerful admin panel. Update news, galleries, events, and admissions yourself — anytime, anywhere. No technical knowledge needed.',
  'price_display'  => 'Rs. 9,999',
  'price_period'   => 'one-time setup — April 2025 offer',
  'price_old'      => 'Rs. 12,999',
  'price_save'     => '🎉 Save Rs. 3,000 this April',
  'domain_note'    => '* Domain registration charges are excluded',
  'btn_bg'         => 'linear-gradient(90deg,#ff00cc,#3333ff)',
  'btn_text'       => 'Claim April Deal Now',
  'tab_color'      => 'pink',
  'features' => [
    ['⚡','Your own admin login panel'],
    ['🖥️','Professional school website'],
    ['📱','Mobile responsive design'],
    ['📝','Manage content yourself'],
    ['📅','Events & announcements'],
    ['👩‍🏫','Staff & faculty profiles'],
    ['📋','Online admissions management'],
    ['🌐','1 year hosting included'],
  ],
  'tc' => [

    /* ====== ENGLISH ====== */
    'en' => [
      ['title'=>'Service Overview','text'=>'Under this plan, Schoozie will design, develop, and deliver a fully dynamic school website with a dedicated admin login panel. You will be able to manage your own website content — including news, events, photos, staff profiles, and admissions — without requiring any technical knowledge.'],
      ['title'=>'April 2025 Offer Terms','points'=>[
        'The discounted price of Rs. 9,999 is valid for clients who make full payment during April 2025 only.',
        'After April 2025, the regular price of Rs. 12,999 will apply.',
        'The offer cannot be combined with any other discount.',
        'Payment must be made in full to lock in the offer price.',
      ]],
      ['title'=>'Payment Terms','points'=>[
        'Full payment of Rs. 9,999 (April offer) or Rs. 12,999 (regular) is required before work begins.',
        'Payment accepted via bank transfer, JazzCash, or EasyPaisa.',
        'Work commences within 24 hours of confirmed payment.',
        'Domain registration and renewal charges are NOT included.',
      ]],
      ['title'=>'What Is Included','points'=>[
        'Custom-designed dynamic school website (up to 8 pages).',
        'Admin login panel for the school (manage your own content).',
        'Mobile-friendly, fully responsive layout.',
        'News, events, announcements management.',
        'Photo gallery management.',
        'Staff and faculty profile section.',
        'Online admissions inquiry management.',
        'First year of web hosting included.',
        'Admin credentials setup and handover.',
        'Basic training on how to use the admin panel (via WhatsApp/video call).',
      ]],
      ['title'=>'What Is NOT Included','points'=>[
        'Domain name purchase or annual renewal.',
        'Fee collection or ERP/student management features.',
        'Custom email accounts.',
        'SEO optimization or paid marketing.',
        'Third-party integrations unless agreed separately.',
        'Ongoing content management by Schoozie (client manages own content).',
      ]],
      ['title'=>'Admin Panel & Credentials','points'=>[
        'A unique admin username and password will be created for your school.',
        'The client is fully responsible for keeping credentials secure.',
        'Schoozie will NOT be responsible for unauthorized access due to password sharing.',
        'Password reset assistance is available via WhatsApp.',
      ]],
      ['title'=>'Delivery Timeline','text'=>'Website will be delivered within 10–14 working days from the date of payment and after submission of all required content. Complex customization requests may extend this timeline and will be communicated in advance.'],
      ['title'=>'Hosting & Renewal','points'=>[
        'First year of hosting is included in the package price.',
        'Annual renewal charge from second year: <strong>Rs. 7,800/year</strong> (domain excluded).',
        'Client will be notified at least 30 days before hosting expiry.',
        'Schoozie reserves the right to take down the website if hosting fees are not renewed.',
      ]],
      ['title'=>'Ownership Rights','points'=>[
        'Content uploaded by the client (text, photos) remains the client\'s property.',
        'Website design, framework, and code remain the property of Schoozie.',
        'The client may not resell, transfer, or copy the website design for any third party.',
      ]],
      ['title'=>'Cancellation & Refund Policy','points'=>[
        'No refund after design or development work has commenced.',
        'Full refund may be requested within 24 hours of payment if work has not yet started.',
        'Schoozie may cancel the service without refund if client provides inappropriate, illegal, or false content.',
      ]],
      ['title'=>'Support Policy','points'=>[
        'Technical support available via WhatsApp (Mon–Sat, 10am–6pm IST).',
        'Response time within 24 hours on working days.',
        'Basic panel usage support is included for 30 days post-launch.',
        'This plan does not include priority or 24/7 support.',
      ]],
      ['title'=>'Governing Terms','text'=>'These terms are governed under Indian law. Disputes will first be handled through mutual discussion. Schoozie reserves the right to update these terms at any time with prior notice via WhatsApp or email.'],
    ],

    /* ====== URDU ====== */
    'ur' => [
      ['title'=>'خدمت کا جائزہ','text'=>'اس پلان کے تحت، اسکوزی آپ کے اسکول کے لیے ایک مکمل ڈائنامک ویب سائٹ تیار کرے گا جس میں ایک مخصوص ایڈمن لاگ ان پینل شامل ہوگا۔ آپ خود اپنی ویب سائٹ کا مواد — خبریں، تقریبات، تصاویر، اسٹاف پروفائل اور داخلے — بغیر کسی تکنیکی علم کے منظم کر سکیں گے۔'],
      ['title'=>'اپریل ۲۰۲۵ آفر کی شرائط','points'=>[
        '۹،۹۹۹ روپے کی رعایتی قیمت صرف ان کلائنٹس کے لیے ہے جو اپریل ۲۰۲۵ کے دوران مکمل ادائیگی کریں۔',
        'اپریل ۲۰۲۵ کے بعد ۱۲،۹۹۹ روپے کی باقاعدہ قیمت لاگو ہوگی۔',
        'یہ آفر کسی دوسری چھوٹ کے ساتھ نہیں ملائی جا سکتی۔',
        'آفر قیمت کو لاک کرنے کے لیے مکمل ادائیگی ضروری ہے۔',
      ]],
      ['title'=>'ادائیگی کی شرائط','points'=>[
        'کام شروع ہونے سے پہلے ۹،۹۹۹ (اپریل آفر) یا ۱۲،۹۹۹ روپے (باقاعدہ) کی مکمل ادائیگی ضروری ہے۔',
        'ادائیگی بینک ٹرانسفر، جاز کیش یا ایزی پیسہ کے ذریعے کی جا سکتی ہے۔',
        'ادائیگی کی تصدیق کے ۲۴ گھنٹوں کے اندر کام شروع ہو جائے گا۔',
        'ڈومین رجسٹریشن اور تجدید کے اخراجات شامل نہیں ہیں۔',
      ]],
      ['title'=>'کیا شامل ہے','points'=>[
        'حسب ضرورت ڈائنامک اسکول ویب سائٹ (۸ صفحات تک)۔',
        'اسکول کے لیے ایڈمن لاگ ان پینل (خود مواد منظم کریں)۔',
        'موبائل فرینڈلی، مکمل ریسپانسیو لے آؤٹ۔',
        'خبریں، تقریبات، اعلانات کا انتظام۔',
        'فوٹو گیلری مینجمنٹ۔',
        'اسٹاف اور فیکلٹی پروفائل سیکشن۔',
        'آن لائن داخلہ انکوائری مینجمنٹ۔',
        'پہلے سال کی ویب ہوسٹنگ شامل۔',
        'ایڈمن اسناد کا سیٹ اپ اور ہینڈ اوور۔',
        'ایڈمن پینل استعمال کی بنیادی تربیت (واٹس ایپ/ویڈیو کال کے ذریعے)۔',
      ]],
      ['title'=>'کیا شامل نہیں ہے','points'=>[
        'ڈومین نام کی خریداری یا سالانہ تجدید۔',
        'فیس کلیکشن یا ERP/طلبا مینجمنٹ کی سہولیات۔',
        'کسٹم ای میل اکاؤنٹس۔',
        'SEO آپٹیمائزیشن یا پیڈ مارکیٹنگ۔',
        'تھرڈ پارٹی انٹیگریشن الگ معاہدے کے بغیر۔',
        'اسکوزی کی طرف سے جاری مواد کا انتظام (کلائنٹ خود مواد منظم کرتا ہے)۔',
      ]],
      ['title'=>'ایڈمن پینل اور اسناد','points'=>[
        'آپ کے اسکول کے لیے ایک منفرد ایڈمن یوزر نیم اور پاس ورڈ بنایا جائے گا۔',
        'کلائنٹ اسناد کو محفوظ رکھنے کا مکمل ذمہ دار ہے۔',
        'پاس ورڈ شیئر کرنے کی وجہ سے غیر مجاز رسائی کے لیے اسکوزی ذمہ دار نہیں ہوگا۔',
        'پاس ورڈ ری سیٹ کی مدد واٹس ایپ کے ذریعے دستیاب ہے۔',
      ]],
      ['title'=>'ڈیلیوری ٹائم لائن','text'=>'ویب سائٹ ادائیگی کی تاریخ سے ۱۰ سے ۱۴ کاری دنوں میں فراہم کی جائے گی، بشرطیکہ تمام مطلوبہ مواد جمع کرا دیا گیا ہو۔ پیچیدہ حسب ضرورت درخواستیں اس ٹائم لائن کو بڑھا سکتی ہیں اور پہلے سے مطلع کیا جائے گا۔'],
      ['title'=>'ہوسٹنگ اور تجدید','points'=>[
        'پہلے سال کی ہوسٹنگ پیکج کی قیمت میں شامل ہے۔',
        'دوسرے سال سے سالانہ تجدید: <strong>۷،۸۰۰ روپے/سال</strong> (ڈومین کے بغیر)۔',
        'ہوسٹنگ میعاد ختم ہونے سے کم از کم ۳۰ دن پہلے کلائنٹ کو مطلع کیا جائے گا۔',
        'اگر ہوسٹنگ فیس تجدید نہ ہو تو اسکوزی ویب سائٹ ہٹانے کا حق رکھتا ہے۔',
      ]],
      ['title'=>'ملکیت کے حقوق','points'=>[
        'کلائنٹ کا اپ لوڈ کردہ مواد (متن، تصاویر) کلائنٹ کی ملکیت رہتا ہے۔',
        'ویب سائٹ ڈیزائن، فریم ورک اور کوڈ اسکوزی کی ملکیت رہتے ہیں۔',
        'کلائنٹ کسی تیسرے فریق کے لیے ویب سائٹ ڈیزائن کو فروخت، منتقل یا کاپی نہیں کر سکتا۔',
      ]],
      ['title'=>'منسوخی اور واپسی کی پالیسی','points'=>[
        'ڈیزائن یا ڈویلپمنٹ کام شروع ہونے کے بعد کوئی واپسی نہیں ہوگی۔',
        'اگر کام ابھی شروع نہیں ہوا تو ادائیگی کے ۲۴ گھنٹوں کے اندر مکمل واپسی کی درخواست کی جا سکتی ہے۔',
        'اگر کلائنٹ نامناسب، غیر قانونی یا غلط مواد فراہم کرے تو اسکوزی بغیر واپسی کے سروس منسوخ کر سکتا ہے۔',
      ]],
      ['title'=>'سپورٹ پالیسی','points'=>[
        'تکنیکی سپورٹ واٹس ایپ کے ذریعے (پیر تا ہفتہ، صبح ۱۰ بجے تا شام ۶ بجے) دستیاب ہے۔',
        'کاری دنوں میں جواب کا وقت ۲۴ گھنٹوں کے اندر ہے۔',
        'لانچ کے بعد ۳۰ دنوں تک بنیادی پینل استعمال کی سپورٹ شامل ہے۔',
        'اس پلان میں ترجیحی یا ۲۴/۷ سپورٹ شامل نہیں ہے۔',
      ]],
      ['title'=>'حاکم شرائط','text'=>'یہ شرائط بھارتی قانون کے تحت ہیں۔ تنازعات کو پہلے باہمی گفتگو سے حل کیا جائے گا۔ اسکوزی واٹس ایپ یا ای میل کے ذریعے پیشگی اطلاع دے کر ان شرائط کو کسی بھی وقت اپ ڈیٹ کرنے کا حق رکھتا ہے۔'],
    ],

    /* ====== HINDI ====== */
    'hi' => [
      ['title'=>'सेवा का अवलोकन','text'=>'इस प्लान के तहत, Schoozie आपके स्कूल के लिए एक पूरी तरह से डायनामिक वेबसाइट तैयार करेगा जिसमें एक समर्पित एडमिन लॉगिन पैनल शामिल होगा। आप खुद अपनी वेबसाइट की सामग्री — समाचार, कार्यक्रम, फ़ोटो, स्टाफ प्रोफाइल और प्रवेश — बिना किसी तकनीकी ज्ञान के प्रबंधित कर सकेंगे।'],
      ['title'=>'अप्रैल 2025 ऑफर की शर्तें','points'=>[
        'Rs. 9,999 की रियायती कीमत केवल उन क्लाइंट्स के लिए है जो अप्रैल 2025 के दौरान पूरा भुगतान करते हैं।',
        'अप्रैल 2025 के बाद Rs. 12,999 की नियमित कीमत लागू होगी।',
        'यह ऑफर किसी अन्य छूट के साथ नहीं जोड़ा जा सकता।',
        'ऑफर मूल्य को लॉक करने के लिए पूरा भुगतान आवश्यक है।',
      ]],
      ['title'=>'भुगतान की शर्तें','points'=>[
        'काम शुरू होने से पहले Rs. 9,999 (अप्रैल ऑफर) या Rs. 12,999 (नियमित) का पूरा भुगतान आवश्यक है।',
        'भुगतान बैंक ट्रांसफर, JazzCash या EasyPaisa के माध्यम से स्वीकार किया जाता है।',
        'पुष्टि के 24 घंटों के भीतर काम शुरू हो जाएगा।',
        'डोमेन पंजीकरण और नवीनीकरण शुल्क शामिल नहीं हैं।',
      ]],
      ['title'=>'क्या शामिल है','points'=>[
        'कस्टम-डिज़ाइन की गई डायनामिक स्कूल वेबसाइट (8 पृष्ठों तक)।',
        'स्कूल के लिए एडमिन लॉगिन पैनल (खुद सामग्री प्रबंधित करें)।',
        'मोबाइल-फ्रेंडली, पूरी तरह रिस्पॉन्सिव लेआउट।',
        'समाचार, कार्यक्रम, घोषणाएं प्रबंधन।',
        'फोटो गैलरी प्रबंधन।',
        'स्टाफ और फैकल्टी प्रोफाइल अनुभाग।',
        'ऑनलाइन प्रवेश जांच प्रबंधन।',
        'पहले वर्ष की वेब होस्टिंग शामिल।',
        'एडमिन क्रेडेंशियल सेटअप और हैंडओवर।',
        'एडमिन पैनल उपयोग की बुनियादी प्रशिक्षण (WhatsApp/वीडियो कॉल के माध्यम से)।',
      ]],
      ['title'=>'क्या शामिल नहीं है','points'=>[
        'डोमेन नाम की खरीद या वार्षिक नवीनीकरण।',
        'शुल्क संग्रह या ERP/छात्र प्रबंधन सुविधाएं।',
        'कस्टम ईमेल खाते।',
        'SEO अनुकूलन या भुगतान विपणन।',
        'अलग समझौते के बिना थर्ड-पार्टी एकीकरण।',
        'Schoozie द्वारा चल रहे सामग्री प्रबंधन (क्लाइंट खुद सामग्री प्रबंधित करता है)।',
      ]],
      ['title'=>'एडमिन पैनल और क्रेडेंशियल','points'=>[
        'आपके स्कूल के लिए एक अद्वितीय एडमिन यूज़रनेम और पासवर्ड बनाया जाएगा।',
        'क्लाइंट क्रेडेंशियल को सुरक्षित रखने के लिए पूरी तरह जिम्मेदार है।',
        'पासवर्ड साझा करने के कारण अनधिकृत पहुंच के लिए Schoozie जिम्मेदार नहीं होगा।',
        'पासवर्ड रीसेट सहायता WhatsApp के माध्यम से उपलब्ध है।',
      ]],
      ['title'=>'डिलीवरी समयसीमा','text'=>'वेबसाइट भुगतान की तारीख से 10-14 कार्य दिवसों के भीतर वितरित की जाएगी, बशर्ते सभी आवश्यक सामग्री जमा कर दी गई हो। जटिल अनुकूलन अनुरोध इस समयसीमा को बढ़ा सकते हैं और पहले से सूचित किया जाएगा।'],
      ['title'=>'होस्टिंग और नवीनीकरण','points'=>[
        'पहले वर्ष की होस्टिंग पैकेज मूल्य में शामिल है।',
        'दूसरे वर्ष से वार्षिक नवीनीकरण शुल्क: <strong>Rs. 7,800/वर्ष</strong> (डोमेन शुल्क अलग)।',
        'होस्टिंग समाप्ति से कम से कम 30 दिन पहले क्लाइंट को सूचित किया जाएगा।',
        'यदि होस्टिंग शुल्क नवीनीकृत नहीं किया जाता तो Schoozie वेबसाइट हटाने का अधिकार रखता है।',
      ]],
      ['title'=>'स्वामित्व अधिकार','points'=>[
        'क्लाइंट द्वारा अपलोड की गई सामग्री (पाठ, फ़ोटो) क्लाइंट की संपत्ति रहती है।',
        'वेबसाइट डिज़ाइन, फ्रेमवर्क और कोड Schoozie की संपत्ति रहते हैं।',
        'क्लाइंट किसी तीसरे पक्ष के लिए वेबसाइट डिज़ाइन को बेच, स्थानांतरित या कॉपी नहीं कर सकता।',
      ]],
      ['title'=>'रद्दीकरण और धनवापसी नीति','points'=>[
        'डिज़ाइन या विकास कार्य शुरू होने के बाद कोई धनवापसी नहीं होगी।',
        'यदि कार्य अभी शुरू नहीं हुआ है तो भुगतान के 24 घंटों के भीतर पूर्ण धनवापसी का अनुरोध किया जा सकता है।',
        'यदि क्लाइंट अनुचित, अवैध या गलत सामग्री प्रदान करे तो Schoozie बिना धनवापसी के सेवा रद्द कर सकता है।',
      ]],
      ['title'=>'सहायता नीति','points'=>[
        'तकनीकी सहायता WhatsApp के माध्यम से (सोम-शनि, सुबह 10 बजे - शाम 6 बजे IST) उपलब्ध है।',
        'कार्य दिवसों पर प्रतिक्रिया समय 24 घंटों के भीतर है।',
        'लॉन्च के बाद 30 दिनों तक बुनियादी पैनल उपयोग सहायता शामिल है।',
        'इस प्लान में प्राथमिकता या 24/7 सहायता शामिल नहीं है।',
      ]],
      ['title'=>'शासी नियम','text'=>'ये शर्तें पाकिस्तानी कानून के तहत हैं। विवादों को पहले आपसी बातचीत से सुलझाया जाएगा। Schoozie WhatsApp या ईमेल के माध्यम से पूर्व सूचना देकर इन शर्तों को कभी भी अपडेट करने का अधिकार रखता है।'],
    ],
  ],
];
include '_plan_layout.php';
